<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove($(MSBuildThisFile), $(MSBuildThisFileDirectory)..))" />

  <ItemGroup>
    <PackageVersion Update="System.Collections.Immutable" Version="10.0.1" />
    <PackageVersion Update="System.IO.Pipelines" Version="10.0.10" />
    <PackageVersion Update="System.Reflection.Metadata" Version="10.0.1" />
    <PackageVersion Update="System.Text.Json" Version="10.0.10" />
  </ItemGroup>
</Project>
