// <auto-generated/>

#nullable enable

namespace StreamJsonRpc.Generated;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
internal class IMyService_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
	, global::IMyService
{
	
	private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> AddPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
	{
		typeof(int),
		typeof(int),
	};
	
	public IMyService_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions? options, long? marshaledObjectHandle, global::System.Action? onDispose)
	    : base(client, options, marshaledObjectHandle, onDispose)
	{
	}
	
	int global::IMyService.Add(int a, int b)
	{
		throw new global::System.NotSupportedException($"The return type 'int' is not supported by the generated proxy method.");
	}
	
	private readonly struct AddNamedArgs1
	{
	    public AddNamedArgs1(int a, int b)
	    {
			this.a = a;
			this.b = b;
		}
		
		public readonly int a;
		
		public readonly int b;
	}
}
