// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMyService2_Proxy))]
partial interface IMyService2
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IMyService2_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IMyService2
	{
		
		private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> Task1NamedArgumentDeclaredTypes1 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
		{
			["name"] = typeof(string),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> Task1PositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
		{
			typeof(string),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<string> Task1ParameterNames1 = new global::System.Collections.Generic.List<string>
		{
			"name",
		};
		
		private string? transformedTask11;
		private int Task1ParameterNameTransformState1;
		private global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type>? Task1TransformedNamedArgumentDeclaredTypes1;
		
		public IMyService2_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
		
		global::System.Threading.Tasks.Task global::IMyService2.Task1(string name)
		{
			if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			
			this.OnCallingMethod("Task1");
			string __rpcMethodName = this.transformedTask11 ??= this.TransformMethodName("Task1", typeof(global::IMyService2));
			int __parameterNameTransformState = this.Task1ParameterNameTransformState1;
			if (__parameterNameTransformState == 0)
			{
			    __parameterNameTransformState = global::StreamJsonRpc.Reflection.CodeGenHelpers.GetParameterNameTransformState(this.Options.ParameterNameTransform, Task1ParameterNames1);
			    this.Task1ParameterNameTransformState1 = __parameterNameTransformState;
			}
			
			bool __useTransformedParameterNames = __parameterNameTransformState == 2;
			global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __namedArgumentTypes = __useTransformedParameterNames ?
			    this.Task1TransformedNamedArgumentDeclaredTypes1 ??= global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateNamedArgumentDeclaredTypes(this.Options.ParameterNameTransform, Task1ParameterNames1, Task1PositionalArgumentDeclaredTypes1) :
			    Task1NamedArgumentDeclaredTypes1;
			global::System.Threading.Tasks.Task __result = this.Options.ServerRequiresNamedArguments ?
			    this.JsonRpc.InvokeWithParameterObjectAsync(__rpcMethodName, ConstructNamedArgs(__useTransformedParameterNames), __namedArgumentTypes, default) :
			    this.JsonRpc.InvokeWithCancellationAsync(__rpcMethodName, [name], Task1PositionalArgumentDeclaredTypes1, default);
			this.OnCalledMethod("Task1");
			
			return __result;
			
			global::System.Collections.Generic.Dictionary<string, object?> ConstructNamedArgs(bool __useTransformedParameterNames)
			{
			    if (__useTransformedParameterNames)
			    {
			        return new()
			        {
				[this.Options.ParameterNameTransform("name")] = name,
			        };
			    }
			
			    return new()
			    {
				["name"] = name,
			    };
			}
		}
	}
}
