// <auto-generated/>

#nullable enable

namespace System.Runtime.CompilerServices
{
#pragma warning disable CS9113
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
    {
    }
#pragma warning restore CS9113
}

#pragma warning disable CS0436 // prefer local types to imported ones

namespace StreamJsonRpc.Generated
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	file static class StreamJsonRpcInterceptor
	{

		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "zFkSg4spW3FE7SpFmVwd82MBAABUZXN0MC5jcw==")]
		internal static T AttachIMyService_Proxy<T>(this global::StreamJsonRpc.JsonRpc jsonRpc)
		    where T : class
		{
		    return (T)(object)new IMyService_Proxy(jsonRpc, null, null, null);
		}

		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "zFkSg4spW3FE7SpFmVwd850BAABUZXN0MC5jcw==")]
		internal static T AttachIMyService2_Proxy<T>(this global::StreamJsonRpc.JsonRpc jsonRpc)
		    where T : class
		{
		    return (T)(object)new IMyService2_Proxy(jsonRpc, null, null, null);
		}
	}
}
