// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class B_IMyRpc_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::B.IMyRpc
	{
		
		private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> JustAnotherCancellationAsyncNamedArgumentDeclaredTypes1 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
		{
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> JustAnotherCancellationAsyncPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
		{
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<string> JustAnotherCancellationAsyncParameterNames1 = new global::System.Collections.Generic.List<string>
		{
		};
		
		private string? transformedJustAnotherCancellationAsync1;
		private int JustAnotherCancellationAsyncParameterNameTransformState1;
		private global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type>? JustAnotherCancellationAsyncTransformedNamedArgumentDeclaredTypes1;
		
		public B_IMyRpc_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
		
		global::System.Threading.Tasks.Task global::B.IMyRpc.JustAnotherCancellationAsync(global::System.Threading.CancellationToken cancellationToken)
		{
			if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			
			this.OnCallingMethod("JustAnotherCancellationAsync");
			string __rpcMethodName = this.transformedJustAnotherCancellationAsync1 ??= this.TransformMethodName("JustAnotherCancellationAsync", typeof(global::B.IMyRpc));
			int __parameterNameTransformState = this.JustAnotherCancellationAsyncParameterNameTransformState1;
			if (__parameterNameTransformState == 0)
			{
			    __parameterNameTransformState = global::StreamJsonRpc.Reflection.CodeGenHelpers.GetParameterNameTransformState(this.Options.ParameterNameTransform, JustAnotherCancellationAsyncParameterNames1);
			    this.JustAnotherCancellationAsyncParameterNameTransformState1 = __parameterNameTransformState;
			}
			
			bool __useTransformedParameterNames = __parameterNameTransformState == 2;
			global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __namedArgumentTypes = __useTransformedParameterNames ?
			    this.JustAnotherCancellationAsyncTransformedNamedArgumentDeclaredTypes1 ??= global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateNamedArgumentDeclaredTypes(this.Options.ParameterNameTransform, JustAnotherCancellationAsyncParameterNames1, JustAnotherCancellationAsyncPositionalArgumentDeclaredTypes1) :
			    JustAnotherCancellationAsyncNamedArgumentDeclaredTypes1;
			global::System.Threading.Tasks.Task __result = this.Options.ServerRequiresNamedArguments ?
			    this.JsonRpc.InvokeWithParameterObjectAsync(__rpcMethodName, ConstructNamedArgs(__useTransformedParameterNames), __namedArgumentTypes, cancellationToken) :
			    this.JsonRpc.InvokeWithCancellationAsync(__rpcMethodName, [], JustAnotherCancellationAsyncPositionalArgumentDeclaredTypes1, cancellationToken);
			this.OnCalledMethod("JustAnotherCancellationAsync");
			
			return __result;
			
			global::System.Collections.Generic.Dictionary<string, object?> ConstructNamedArgs(bool __useTransformedParameterNames)
			{
			    if (__useTransformedParameterNames)
			    {
			        return new()
			        {
			        };
			    }
			
			    return new()
			    {
			    };
			}
		}
	}
}
