// <auto-generated/>

#nullable enable

namespace System.Runtime.CompilerServices
{
#pragma warning disable CS9113
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
    {
    }
#pragma warning restore CS9113
}

#pragma warning disable CS0436 // prefer local types to imported ones

namespace StreamJsonRpc.Generated
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	file static class StreamJsonRpcInterceptor
	{

		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "aW+5aLHFPI2QBoMmbUS8FToBAABUZXN0MC5jcw==")]
		internal static T AttachIMyService_Proxy<T>(this global::StreamJsonRpc.JsonRpc jsonRpc, global::StreamJsonRpc.JsonRpcProxyOptions? options)
		    where T : class
		    => (T)(object)new IMyService_Proxy(jsonRpc, new() { ContractInterface = typeof(T), Options = options });
		
		private static global::StreamJsonRpc.IJsonRpcClientProxy StartListening(global::StreamJsonRpc.IJsonRpcClientProxy proxy)
		{
		    proxy.JsonRpc.StartListening();
		    return proxy;
		}
	}
}
