// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMarshalableSobURHW8_Proxy))]
partial interface IMarshalable
{
}

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMarshalableSobURHW8_Proxy))]
partial interface IOptional
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IMarshalableSobURHW8_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IMarshalable
		, global::IOptional
	{
		
		public IMarshalableSobURHW8_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
	}
}
