// <auto-generated/>

#nullable enable

[assembly: global::StreamJsonRpc.Reflection.RpcProxyMappingAttribute(typeof(global::IFoo), typeof(global::StreamJsonRpc.Proxies.IFoo_Proxy))]

namespace StreamJsonRpc.Proxies;

internal class IFoo_Proxy : global::IFoo, global::StreamJsonRpc.Reflection.IJsonRpcClientProxyInternal
{
	private readonly global::StreamJsonRpc.JsonRpc client;
	private readonly global::StreamJsonRpc.JsonRpcProxyOptions options;
	private readonly global::System.Action? onDispose;
	private readonly long? marshaledObjectHandle;
	
	private global::System.EventHandler<string>? callingMethod;
	private global::System.EventHandler<string>? calledMethod;
	private bool disposed;
	
	private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> SayHiNamedArgumentDeclaredTypes1 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
	{
	};
	
	private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> SayHiPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
	{
	};
	
	private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> SayHiNamedArgumentDeclaredTypes2 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
	{
		["name"] = typeof(string),
	};
	
	private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> SayHiPositionalArgumentDeclaredTypes2 = new global::System.Collections.Generic.List<global::System.Type>
	{
		typeof(string),
	};
	
	private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> SayHiNamedArgumentDeclaredTypes3 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
	{
		["name"] = typeof(string),
		["age"] = typeof(int),
	};
	
	private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> SayHiPositionalArgumentDeclaredTypes3 = new global::System.Collections.Generic.List<global::System.Type>
	{
		typeof(string),
		typeof(int),
	};
	public IFoo_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions options, long? marshaledObjectHandle, global::System.Action? onDispose)
	{
	    this.client = client ?? throw new global::System.ArgumentNullException(nameof(client));
	    this.options = options ?? throw new global::System.ArgumentNullException(nameof(options));
	    this.marshaledObjectHandle = marshaledObjectHandle;
	    this.onDispose = onDispose;
	}
	
	event global::System.EventHandler<string> global::StreamJsonRpc.Reflection.IJsonRpcClientProxyInternal.CallingMethod
	{
	    add => this.callingMethod += value;
	    remove => this.callingMethod -= value;
	}
	
	event global::System.EventHandler<string> global::StreamJsonRpc.Reflection.IJsonRpcClientProxyInternal.CalledMethod
	{
	    add => this.calledMethod += value;
	    remove => this.calledMethod -= value;
	}
	
	global::StreamJsonRpc.JsonRpc global::StreamJsonRpc.IJsonRpcClientProxy.JsonRpc => this.client;
	
	bool global::Microsoft.IDisposableObservable.IsDisposed => this.disposed;
	
	long? global::StreamJsonRpc.Reflection.IJsonRpcClientProxyInternal.MarshaledObjectHandle => this.marshaledObjectHandle;
	
	void global::System.IDisposable.Dispose()
	{
	    if (this.disposed)
	    {
	        return;
	    }
	    this.disposed = true;
	
	    if (this.onDispose is not null)
	    {
	        this.onDispose();
	    }
	    else
	    {
	        client.Dispose();
	    }
	}
	
	public global::System.Threading.Tasks.Task SayHi()
	{
		if (this.disposed) throw new global::System.ObjectDisposedException(nameof(IFoo_Proxy));
		
		this.callingMethod?.Invoke(this, "SayHi");
		string rpcMethodName = this.options.MethodNameTransform("SayHi");
		global::System.Threading.Tasks.Task result = this.options.ServerRequiresNamedArguments ?
		    this.client.InvokeWithParameterObjectAsync(rpcMethodName, new SayHiNamedArgs1(), SayHiNamedArgumentDeclaredTypes1, default) :
		    this.client.InvokeWithCancellationAsync(rpcMethodName, [], SayHiPositionalArgumentDeclaredTypes1, default);
		this.calledMethod?.Invoke(this, "SayHi");
		
		return result;
	}
	
	public global::System.Threading.Tasks.Task SayHi(string name)
	{
		if (this.disposed) throw new global::System.ObjectDisposedException(nameof(IFoo_Proxy));
		
		this.callingMethod?.Invoke(this, "SayHi");
		string rpcMethodName = this.options.MethodNameTransform("SayHi");
		global::System.Threading.Tasks.Task result = this.options.ServerRequiresNamedArguments ?
		    this.client.InvokeWithParameterObjectAsync(rpcMethodName, new SayHiNamedArgs2(name), SayHiNamedArgumentDeclaredTypes2, default) :
		    this.client.InvokeWithCancellationAsync(rpcMethodName, [name], SayHiPositionalArgumentDeclaredTypes2, default);
		this.calledMethod?.Invoke(this, "SayHi");
		
		return result;
	}
	
	public global::System.Threading.Tasks.Task SayHi(string name, int age)
	{
		if (this.disposed) throw new global::System.ObjectDisposedException(nameof(IFoo_Proxy));
		
		this.callingMethod?.Invoke(this, "SayHi");
		string rpcMethodName = this.options.MethodNameTransform("SayHi");
		global::System.Threading.Tasks.Task result = this.options.ServerRequiresNamedArguments ?
		    this.client.InvokeWithParameterObjectAsync(rpcMethodName, new SayHiNamedArgs3(name, age), SayHiNamedArgumentDeclaredTypes3, default) :
		    this.client.InvokeWithCancellationAsync(rpcMethodName, [name, age], SayHiPositionalArgumentDeclaredTypes3, default);
		this.calledMethod?.Invoke(this, "SayHi");
		
		return result;
	}
	
	private readonly struct SayHiNamedArgs1
	{
	    public SayHiNamedArgs1()
	    {
		}
	}
	
	private readonly struct SayHiNamedArgs2
	{
	    public SayHiNamedArgs2(string name)
	    {
			this.name = name;
		}
		
		public string name { get; }
	}
	
	private readonly struct SayHiNamedArgs3
	{
	    public SayHiNamedArgs3(string name, int age)
	    {
			this.name = name;
			this.age = age;
		}
		
		public string name { get; }
		
		public int age { get; }
	}
}
