// <auto-generated/>

#nullable enable

namespace StreamJsonRpc.Proxies;

internal class RpcProxyNoName(
    global::StreamJsonRpc.JsonRpc client,
    global::StreamJsonRpc.JsonRpcProxyOptions options,
    long? marshaledObjectHandle,
    global::System.Action onDispose) : global::IMyRpc, global::StreamJsonRpc.IJsonRpcClientProxyInternal
{
    private global::System.EventHandler<string>? callingMethod;
    private global::System.EventHandler<string>? calledMethod;
    private bool disposed;

    global::StreamJsonRpc.JsonRpc global::StreamJsonRpc.IJsonRpcClientProxy.JsonRpc => client;

    bool global::Microsoft.IDisposableObservable.IsDisposed => this.disposed;

    long? global::StreamJsonRpc.IJsonRpcClientProxyInternal.MarshaledObjectHandle => marshaledObjectHandle;

    event global::System.EventHandler<string> global::StreamJsonRpc.IJsonRpcClientProxyInternal.CallingMethod
    {
        add => this.callingMethod += value;
        remove => this.callingMethod -= value;
    }

    event global::System.EventHandler<string> global::StreamJsonRpc.IJsonRpcClientProxyInternal.CalledMethod
    {
        add => this.calledMethod += value;
        remove => this.calledMethod -= value;
    }

    public void Dispose()
    {
        if (this.disposed)
        {
            return;
        }
        this.disposed = true;

        if (onDispose is not null)
        {
            onDispose();
        }
        else
        {
            client.Dispose();
        }
    }
	private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> MyMethodAsyncNamedArgumentDeclaredTypes = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
	{
	};
	private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> MyMethodAsyncPositionalArgumentDeclaredTypes = new global::System.Collections.Generic.List<global::System.Type>
	{
	};
	private record MyMethodAsyncNamedArgs();
	
	public global::System.Threading.Tasks.Task MyMethodAsync(global::System.Threading.CancellationToken cancellationToken)
	{
	    if (this.disposed)
	    {
	        throw new global::System.ObjectDisposedException(nameof(RpcProxyNoName));
	    }
	
	    this.callingMethod?.Invoke(this, "MyMethodAsync");
	    string rpcMethodName = options.MethodNameTransform("MyMethodAsync");
	    global::System.Threading.Tasks.Task result;
	    if (options.ServerRequiresNamedArguments)
	    {
	        result = client.InvokeWithParameterObjectAsync(rpcMethodName, new MyMethodAsyncNamedArgs(), MyMethodAsyncNamedArgumentDeclaredTypes, default);
	    }
	    else
	    {
	        result = client.InvokeWithCancellationAsync(rpcMethodName, [], MyMethodAsyncPositionalArgumentDeclaredTypes, default);
	    }
	
	    this.calledMethod?.Invoke(this, "MyMethodAsync");
	
	    return result;
	}
}
