// <auto-generated/>

namespace StreamJsonRpc.Proxies;

internal class RpcProxy(global::StreamJsonRpc.JsonRpc client) : global::IMyRpc
{
	public global::System.Threading.Tasks.Task MyMethodAsync(global::System.Threading.CancellationToken cancellationToken)
	{
		throw new System.NotImplementedException();
	}
}
