// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.SomeExperimentalInterfaceMDGoEVkn_Proxy))]
partial interface SomeExperimentalInterface
{
}

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.SomeExperimentalInterfaceMDGoEVkn_Proxy))]
partial interface SomeExperimentalInterface2
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class SomeExperimentalInterfaceMDGoEVkn_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::SomeExperimentalInterface
		, global::SomeExperimentalInterface2
	{
		
		private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> AddAsyncNamedArgumentDeclaredTypes1 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
		{
			["a"] = typeof(int),
			["t"] = typeof(global::CustomType),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> AddAsyncPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
		{
			typeof(int),
			typeof(global::CustomType),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<string> AddAsyncParameterNames1 = new global::System.Collections.Generic.List<string>
		{
			"a",
			"t",
		};
		
		private string? transformedAddAsync1;
		private int AddAsyncParameterNameTransformState1;
		private global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type>? AddAsyncTransformedNamedArgumentDeclaredTypes1;
		
		private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> AddAsyncNamedArgumentDeclaredTypes2 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
		{
			["a"] = typeof(int),
			["t"] = typeof(global::CustomType),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> AddAsyncPositionalArgumentDeclaredTypes2 = new global::System.Collections.Generic.List<global::System.Type>
		{
			typeof(int),
			typeof(global::CustomType),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<string> AddAsyncParameterNames2 = new global::System.Collections.Generic.List<string>
		{
			"a",
			"t",
		};
		
		private string? transformedAddAsync2;
		private int AddAsyncParameterNameTransformState2;
		private global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type>? AddAsyncTransformedNamedArgumentDeclaredTypes2;
		
		public SomeExperimentalInterfaceMDGoEVkn_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
		
		global::System.Threading.Tasks.Task<int> global::SomeExperimentalInterface.AddAsync(int a, global::CustomType t, global::System.Threading.CancellationToken token)
		{
			if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			
			this.OnCallingMethod("AddAsync");
			string __rpcMethodName = this.transformedAddAsync1 ??= this.TransformMethodName("AddAsync", typeof(global::SomeExperimentalInterface));
			int __parameterNameTransformState = this.AddAsyncParameterNameTransformState1;
			if (__parameterNameTransformState == 0)
			{
			    __parameterNameTransformState = global::StreamJsonRpc.Reflection.CodeGenHelpers.GetParameterNameTransformState(this.Options.ParameterNameTransform, AddAsyncParameterNames1);
			    this.AddAsyncParameterNameTransformState1 = __parameterNameTransformState;
			}
			
			bool __useTransformedParameterNames = __parameterNameTransformState == 2;
			global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __namedArgumentTypes = __useTransformedParameterNames ?
			    this.AddAsyncTransformedNamedArgumentDeclaredTypes1 ??= global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateNamedArgumentDeclaredTypes(this.Options.ParameterNameTransform, AddAsyncParameterNames1, AddAsyncPositionalArgumentDeclaredTypes1) :
			    AddAsyncNamedArgumentDeclaredTypes1;
			global::System.Threading.Tasks.Task<int> __result = this.Options.ServerRequiresNamedArguments ?
			    this.JsonRpc.InvokeWithParameterObjectAsync<int>(__rpcMethodName, ConstructNamedArgs(__useTransformedParameterNames), __namedArgumentTypes, token) :
			    this.JsonRpc.InvokeWithCancellationAsync<int>(__rpcMethodName, [a, t], AddAsyncPositionalArgumentDeclaredTypes1, token);
			this.OnCalledMethod("AddAsync");
			
			return __result;
			
			global::System.Collections.Generic.Dictionary<string, object?> ConstructNamedArgs(bool __useTransformedParameterNames)
			{
			    if (__useTransformedParameterNames)
			    {
			        return new()
			        {
				[this.Options.ParameterNameTransform("a")] = a,
				[this.Options.ParameterNameTransform("t")] = t,
			        };
			    }
			
			    return new()
			    {
				["a"] = a,
				["t"] = t,
			    };
			}
		}
		
		global::System.Threading.Tasks.Task<int> global::SomeExperimentalInterface2.AddAsync(int a, global::CustomType t, global::System.Threading.CancellationToken token)
		{
			if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			
			this.OnCallingMethod("AddAsync");
			string __rpcMethodName = this.transformedAddAsync2 ??= this.TransformMethodName("AddAsync", typeof(global::SomeExperimentalInterface2));
			int __parameterNameTransformState = this.AddAsyncParameterNameTransformState2;
			if (__parameterNameTransformState == 0)
			{
			    __parameterNameTransformState = global::StreamJsonRpc.Reflection.CodeGenHelpers.GetParameterNameTransformState(this.Options.ParameterNameTransform, AddAsyncParameterNames2);
			    this.AddAsyncParameterNameTransformState2 = __parameterNameTransformState;
			}
			
			bool __useTransformedParameterNames = __parameterNameTransformState == 2;
			global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __namedArgumentTypes = __useTransformedParameterNames ?
			    this.AddAsyncTransformedNamedArgumentDeclaredTypes2 ??= global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateNamedArgumentDeclaredTypes(this.Options.ParameterNameTransform, AddAsyncParameterNames2, AddAsyncPositionalArgumentDeclaredTypes2) :
			    AddAsyncNamedArgumentDeclaredTypes2;
			global::System.Threading.Tasks.Task<int> __result = this.Options.ServerRequiresNamedArguments ?
			    this.JsonRpc.InvokeWithParameterObjectAsync<int>(__rpcMethodName, ConstructNamedArgs(__useTransformedParameterNames), __namedArgumentTypes, token) :
			    this.JsonRpc.InvokeWithCancellationAsync<int>(__rpcMethodName, [a, t], AddAsyncPositionalArgumentDeclaredTypes2, token);
			this.OnCalledMethod("AddAsync");
			
			return __result;
			
			global::System.Collections.Generic.Dictionary<string, object?> ConstructNamedArgs(bool __useTransformedParameterNames)
			{
			    if (__useTransformedParameterNames)
			    {
			        return new()
			        {
				[this.Options.ParameterNameTransform("a")] = a,
				[this.Options.ParameterNameTransform("t")] = t,
			        };
			    }
			
			    return new()
			    {
				["a"] = a,
				["t"] = t,
			    };
			}
		}
	}
}
