// <auto-generated/>

#nullable enable

namespace StreamJsonRpc.Generated;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
internal class IMyService_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
	, global::IMyService
{
	
	private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> GetNullableIntAsyncPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
	{
		typeof(string),
	};
	
	private string? transformedGetNullableIntAsync1;
	
	public IMyService_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions? options, long? marshaledObjectHandle, global::System.Action? onDispose)
	    : base(client, options, marshaledObjectHandle, onDispose)
	{
	}
	
	global::System.Threading.Tasks.Task<object?> global::IMyService.GetNullableIntAsync(string? value)
	{
		if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
		
		this.OnCallingMethod("GetNullableIntAsync");
		string rpcMethodName = this.transformedGetNullableIntAsync1 ??= this.Options.MethodNameTransform("GetNullableIntAsync");
		global::System.Threading.Tasks.Task<object?> result = this.Options.ServerRequiresNamedArguments ?
		    this.JsonRpc.InvokeWithParameterObjectAsync<object?>(rpcMethodName, new GetNullableIntAsyncNamedArgs1(value), null, default) :
		    this.JsonRpc.InvokeWithCancellationAsync<object?>(rpcMethodName, [value], GetNullableIntAsyncPositionalArgumentDeclaredTypes1, default);
		this.OnCalledMethod("GetNullableIntAsync");
		
		return result;
	}
	
	private readonly struct GetNullableIntAsyncNamedArgs1
	{
	    public GetNullableIntAsyncNamedArgs1(string? value)
	    {
			this.value = value;
		}
		
		public readonly string? value;
	}
}
