// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IGenericMarshalable_Proxy<,>))]
[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IGenericMarshalable_Proxy<int, string>))]
partial interface IGenericMarshalable<T1, T2>
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IGenericMarshalable_Proxy<T1, T2> : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IGenericMarshalable<T1, T2>
	{
		
		private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> DoSomethingWithParameterAsyncNamedArgumentDeclaredTypes1 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
		{
			["parameter"] = typeof(T2),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> DoSomethingWithParameterAsyncPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
		{
			typeof(T2),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<string> DoSomethingWithParameterAsyncParameterNames1 = new global::System.Collections.Generic.List<string>
		{
			"parameter",
		};
		
		private string? transformedDoSomethingWithParameterAsync1;
		private int DoSomethingWithParameterAsyncParameterNameTransformState1;
		private global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type>? DoSomethingWithParameterAsyncTransformedNamedArgumentDeclaredTypes1;
		
		public IGenericMarshalable_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
		
		global::System.Threading.Tasks.Task<T1> global::IGenericMarshalable<T1, T2>.DoSomethingWithParameterAsync(T2 parameter)
		{
			if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			
			this.OnCallingMethod("DoSomethingWithParameterAsync");
			string __rpcMethodName = this.transformedDoSomethingWithParameterAsync1 ??= this.TransformMethodName("DoSomethingWithParameterAsync", typeof(global::IGenericMarshalable<T1, T2>));
			int __parameterNameTransformState = this.DoSomethingWithParameterAsyncParameterNameTransformState1;
			if (__parameterNameTransformState == 0)
			{
			    __parameterNameTransformState = global::StreamJsonRpc.Reflection.CodeGenHelpers.GetParameterNameTransformState(this.Options.ParameterNameTransform, DoSomethingWithParameterAsyncParameterNames1);
			    this.DoSomethingWithParameterAsyncParameterNameTransformState1 = __parameterNameTransformState;
			}
			
			bool __useTransformedParameterNames = __parameterNameTransformState == 2;
			global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __namedArgumentTypes = __useTransformedParameterNames ?
			    this.DoSomethingWithParameterAsyncTransformedNamedArgumentDeclaredTypes1 ??= global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateNamedArgumentDeclaredTypes(this.Options.ParameterNameTransform, DoSomethingWithParameterAsyncParameterNames1, DoSomethingWithParameterAsyncPositionalArgumentDeclaredTypes1) :
			    DoSomethingWithParameterAsyncNamedArgumentDeclaredTypes1;
			global::System.Threading.Tasks.Task<T1> __result = this.Options.ServerRequiresNamedArguments ?
			    this.JsonRpc.InvokeWithParameterObjectAsync<T1>(__rpcMethodName, ConstructNamedArgs(__useTransformedParameterNames), __namedArgumentTypes, default) :
			    this.JsonRpc.InvokeWithCancellationAsync<T1>(__rpcMethodName, [parameter], DoSomethingWithParameterAsyncPositionalArgumentDeclaredTypes1, default);
			this.OnCalledMethod("DoSomethingWithParameterAsync");
			
			return __result;
			
			global::System.Collections.Generic.Dictionary<string, object?> ConstructNamedArgs(bool __useTransformedParameterNames)
			{
			    if (__useTransformedParameterNames)
			    {
			        return new()
			        {
				[this.Options.ParameterNameTransform("parameter")] = parameter,
			        };
			    }
			
			    return new()
			    {
				["parameter"] = parameter,
			    };
			}
		}
	}
}
