// <auto-generated/>

#nullable enable

namespace System.Runtime.CompilerServices
{
#pragma warning disable CS9113
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
    {
    }
#pragma warning restore CS9113
}

#pragma warning disable CS0436 // prefer local types to imported ones

namespace StreamJsonRpc.Generated
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	file static class StreamJsonRpcInterceptor
	{

		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "a5c1GcY72+owQKc0sumzJQgBAABUZXN0MC5jcw==")]
		internal static T Attach_Unknown<T>(this global::StreamJsonRpc.JsonRpc jsonRpc)
		    where T : class
		    => (T)(object)global::StreamJsonRpc.Reflection.ProxyBase.CreateProxy(jsonRpc, new() { ContractInterface = typeof(T) }, false);
		
		private static global::StreamJsonRpc.IJsonRpcClientProxy StartListening(global::StreamJsonRpc.IJsonRpcClientProxy proxy)
		{
		    proxy.JsonRpc.StartListening();
		    return proxy;
		}
	}
}
