// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMarshalableWithEvents_Proxy))]
partial interface IMarshalableWithEvents
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IMarshalableWithEvents_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IMarshalableWithEvents
	{
		
		public IMarshalableWithEvents_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
			this.JsonRpc.AddLocalRpcMethod(this.TransformEventName("Changed", typeof(global::IMarshalableWithEvents)), this.OnChanged);
		}
		
		public event global::System.EventHandler? Changed;
		
		protected virtual void OnChanged(global::System.EventArgs args) => this.Changed?.Invoke(this, args);
	}
}
