// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones

namespace NS
{
	partial class Wrapper
	{
		[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.NS_Wrapper_IMarshalablegBnetfdo_Proxy))]
		partial interface IMarshalable
		{
		}
	}
}

namespace NS
{
	partial class Wrapper
	{
		[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.NS_Wrapper_IMarshalablegBnetfdo_Proxy))]
		partial interface IOptional
		{
		}
	}
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class NS_Wrapper_IMarshalablegBnetfdo_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::NS.Wrapper.IMarshalable
		, global::NS.Wrapper.IOptional
	{
		
		public NS_Wrapper_IMarshalablegBnetfdo_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
	}
}
