// <auto-generated/>

#nullable enable

#pragma warning disable CS0436 // Prefer local types to imported ones
[assembly: global::StreamJsonRpc.Reflection.RpcProxyMappingAttribute(typeof(IMyService), typeof(StreamJsonRpc.Generated.IMyService_Proxy))]
#pragma warning restore CS0436

namespace StreamJsonRpc.Generated;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
internal class IMyService_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
	, global::IMyService
{
	
	public IMyService_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions? options, long? marshaledObjectHandle, global::System.Action? onDispose)
	    : base(client, options, marshaledObjectHandle, onDispose)
	{
	}
}
