// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IHaveNestedTypes_Proxy))]
partial interface IHaveNestedTypes
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IHaveNestedTypes_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IHaveNestedTypes
	{
		
		private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> DoSomethingAsyncNamedArgumentDeclaredTypes1 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
		{
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> DoSomethingAsyncPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
		{
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<string> DoSomethingAsyncParameterNames1 = new global::System.Collections.Generic.List<string>
		{
		};
		
		private string? transformedDoSomethingAsync1;
		private int DoSomethingAsyncParameterNameTransformState1;
		private global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type>? DoSomethingAsyncTransformedNamedArgumentDeclaredTypes1;
		
		public IHaveNestedTypes_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
		
		global::System.Threading.Tasks.Task global::IHaveNestedTypes.DoSomethingAsync()
		{
			if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			
			this.OnCallingMethod("DoSomethingAsync");
			string __rpcMethodName = this.transformedDoSomethingAsync1 ??= this.TransformMethodName("DoSomethingAsync", typeof(global::IHaveNestedTypes));
			int __parameterNameTransformState = this.DoSomethingAsyncParameterNameTransformState1;
			if (__parameterNameTransformState == 0)
			{
			    __parameterNameTransformState = global::StreamJsonRpc.Reflection.CodeGenHelpers.GetParameterNameTransformState(this.Options.ParameterNameTransform, DoSomethingAsyncParameterNames1);
			    this.DoSomethingAsyncParameterNameTransformState1 = __parameterNameTransformState;
			}
			
			bool __useTransformedParameterNames = __parameterNameTransformState == 2;
			global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __namedArgumentTypes = __useTransformedParameterNames ?
			    this.DoSomethingAsyncTransformedNamedArgumentDeclaredTypes1 ??= global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateNamedArgumentDeclaredTypes(this.Options.ParameterNameTransform, DoSomethingAsyncParameterNames1, DoSomethingAsyncPositionalArgumentDeclaredTypes1) :
			    DoSomethingAsyncNamedArgumentDeclaredTypes1;
			global::System.Threading.Tasks.Task __result = this.Options.ServerRequiresNamedArguments ?
			    this.JsonRpc.InvokeWithParameterObjectAsync(__rpcMethodName, ConstructNamedArgs(__useTransformedParameterNames), __namedArgumentTypes, default) :
			    this.JsonRpc.InvokeWithCancellationAsync(__rpcMethodName, [], DoSomethingAsyncPositionalArgumentDeclaredTypes1, default);
			this.OnCalledMethod("DoSomethingAsync");
			
			return __result;
			
			global::System.Collections.Generic.Dictionary<string, object?> ConstructNamedArgs(bool __useTransformedParameterNames)
			{
			    if (__useTransformedParameterNames)
			    {
			        return new()
			        {
			        };
			    }
			
			    return new()
			    {
			    };
			}
		}
	}
}
