// <auto-generated/>

#nullable enable

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMyServiceZiHkAQOD_Proxy))]
partial interface IMyService
{
}

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMyServiceZiHkAQOD_Proxy))]
partial interface IMyService2
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IMyServiceZiHkAQOD_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IMyService
		, global::IMyService2
	{
		
		public IMyServiceZiHkAQOD_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions? options, long? marshaledObjectHandle, global::System.Action? onDispose, ReadOnlyMemory<Type>? requestedInterfaces)
		    : base(client, options, marshaledObjectHandle, onDispose, requestedInterfaces)
		{
		}
	}
}
