// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMyServiceYOaIB1ve_Proxy))]
partial interface IMyService
{
}

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMyServiceYOaIB1ve_Proxy))]
partial interface IMyService2
{
}

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IMyServiceYOaIB1ve_Proxy))]
partial interface IMyService3
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IMyServiceYOaIB1ve_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IMyService
		, global::IMyService2
		, global::IMyService3
	{
		
		public IMyServiceYOaIB1ve_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
	}
}
