// <auto-generated/>

#nullable enable

namespace StreamJsonRpc.Generated;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
internal class IFoo_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
	, global::IFoo
{
	
	private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> DisposePositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
	{
	};
	
	private string? transformedDispose1;
	
	public IFoo_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions? options, long? marshaledObjectHandle, global::System.Action? onDispose)
	    : base(client, options, marshaledObjectHandle, onDispose)
	{
	}
	
	global::System.Threading.Tasks.Task global::IFoo.Dispose()
	{
		if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
		
		this.OnCallingMethod("Dispose");
		string rpcMethodName = this.transformedDispose1 ??= this.Options.MethodNameTransform("Dispose");
		global::System.Threading.Tasks.Task result = this.Options.ServerRequiresNamedArguments ?
		    this.JsonRpc.InvokeWithParameterObjectAsync(rpcMethodName, new DisposeNamedArgs1(), null, default) :
		    this.JsonRpc.InvokeWithCancellationAsync(rpcMethodName, [], DisposePositionalArgumentDeclaredTypes1, default);
		this.OnCalledMethod("Dispose");
		
		return result;
	}
	
	private readonly struct DisposeNamedArgs1
	{
	    public DisposeNamedArgs1()
	    {
		}
	}
}
