// <auto-generated/>

#nullable enable

#pragma warning disable CS0436 // Prefer local types to imported ones
[assembly: global::StreamJsonRpc.Reflection.RpcProxyMappingAttribute(typeof(IFoo), typeof(StreamJsonRpc.Generated.IFoo_Proxy))]
#pragma warning restore CS0436

namespace StreamJsonRpc.Generated;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
internal class IFoo_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
	, global::IFoo
{
	
	public IFoo_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions? options, long? marshaledObjectHandle, global::System.Action? onDispose)
	    : base(client, options, marshaledObjectHandle, onDispose)
	{
		this.JsonRpc.AddLocalRpcMethod(this.Options.EventNameTransform("MyEvent"), this.OnMyEvent);
		this.JsonRpc.AddLocalRpcMethod(this.Options.EventNameTransform("MyGenericEvent"), this.OnMyGenericEvent);
	}
	
	public event global::System.EventHandler? MyEvent;
	
	protected virtual void OnMyEvent(global::System.EventArgs args) => this.MyEvent?.Invoke(this, args);
	
	public event global::System.EventHandler<string>? MyGenericEvent;
	
	protected virtual void OnMyGenericEvent(string args) => this.MyGenericEvent?.Invoke(this, args);
}
