// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones
#pragma warning disable // Disable all warnings so that [Experimental] APIs don't flag anything.

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IAsyncTaskMonitor_Proxy))]
partial interface IAsyncTaskMonitor
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	internal class IAsyncTaskMonitor_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IAsyncTaskMonitor
	{
		
		private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> OnCompletedNamedArgumentDeclaredTypes1 = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
		{
			["rpcMethodName"] = typeof(string),
			["result"] = typeof(int),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> OnCompletedPositionalArgumentDeclaredTypes1 = new global::System.Collections.Generic.List<global::System.Type>
		{
			typeof(string),
			typeof(int),
		};
		
		private static readonly global::System.Collections.Generic.IReadOnlyList<string> OnCompletedParameterNames1 = new global::System.Collections.Generic.List<string>
		{
			"rpcMethodName",
			"result",
		};
		
		private string? transformedOnCompleted1;
		private int OnCompletedParameterNameTransformState1;
		private global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type>? OnCompletedTransformedNamedArgumentDeclaredTypes1;
		
		public IAsyncTaskMonitor_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.Reflection.ProxyInputs inputs)
		    : base(client, inputs)
		{
		}
		
		global::System.Threading.Tasks.Task global::IAsyncTaskMonitor.OnCompleted(string rpcMethodName, int result, global::System.Threading.CancellationToken cancellationToken)
		{
			if (this.IsDisposed) throw new global::System.ObjectDisposedException(this.GetType().FullName);
			
			this.OnCallingMethod("OnCompleted");
			string __rpcMethodName = this.transformedOnCompleted1 ??= this.TransformMethodName("OnCompleted", typeof(global::IAsyncTaskMonitor));
			int __parameterNameTransformState = this.OnCompletedParameterNameTransformState1;
			if (__parameterNameTransformState == 0)
			{
			    __parameterNameTransformState = global::StreamJsonRpc.Reflection.CodeGenHelpers.GetParameterNameTransformState(this.Options.ParameterNameTransform, OnCompletedParameterNames1);
			    this.OnCompletedParameterNameTransformState1 = __parameterNameTransformState;
			}
			
			bool __useTransformedParameterNames = __parameterNameTransformState == 2;
			global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> __namedArgumentTypes = __useTransformedParameterNames ?
			    this.OnCompletedTransformedNamedArgumentDeclaredTypes1 ??= global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateNamedArgumentDeclaredTypes(this.Options.ParameterNameTransform, OnCompletedParameterNames1, OnCompletedPositionalArgumentDeclaredTypes1) :
			    OnCompletedNamedArgumentDeclaredTypes1;
			global::System.Threading.Tasks.Task __result = this.Options.ServerRequiresNamedArguments ?
			    this.JsonRpc.InvokeWithParameterObjectAsync(__rpcMethodName, ConstructNamedArgs(__useTransformedParameterNames), __namedArgumentTypes, cancellationToken) :
			    this.JsonRpc.InvokeWithCancellationAsync(__rpcMethodName, [rpcMethodName, result], OnCompletedPositionalArgumentDeclaredTypes1, cancellationToken);
			this.OnCalledMethod("OnCompleted");
			
			return __result;
			
			global::System.Collections.Generic.Dictionary<string, object?> ConstructNamedArgs(bool __useTransformedParameterNames)
			{
			    if (__useTransformedParameterNames)
			    {
			        return new()
			        {
				[this.Options.ParameterNameTransform("rpcMethodName")] = rpcMethodName,
				[this.Options.ParameterNameTransform("result")] = result,
			        };
			    }
			
			    return new()
			    {
				["rpcMethodName"] = rpcMethodName,
				["result"] = result,
			    };
			}
		}
	}
}
