// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;

namespace StreamJsonRpc.Analyzers;

/// <summary>
/// Source generator for StreamJsonRpc proxies.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class ProxyGenerator : IIncrementalGenerator
{
    private enum SpecialType
    {
        Other,
        Void,
        Task,
        ValueTask,
        IAsyncEnumerable,
        CancellationToken,
    }

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<DataModel?> proxyProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            Types.RpcProxyAttribute.FullName,
            (node, cancellationToken) => true,
            (context, cancellationToken) =>
            {
                if (context.TargetSymbol is not INamedTypeSymbol iface)
                {
                    return null;
                }

                if (!KnownSymbols.TryCreate(context.SemanticModel.Compilation, out KnownSymbols? symbols))
                {
                    return null;
                }

                ImmutableEquatableArray<MethodModel> methods = new([..
                    iface.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Select(method => MethodModel.Create(method, symbols))]);

                string fileNamePrefix = context.TargetSymbol.ToDisplayString(GenerationHelpers.QualifiedNameOnlyFormat);
                return new DataModel(
                    fileNamePrefix,
                    context.TargetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    methods);
            });

        // TODO:
        // * Generate an interceptor for StreamJsonRpc methods that take RPC interfaces and generate proxies
        //   that redirects to methods that accept our source generated proxy types.

        context.RegisterSourceOutput(proxyProvider, this.GenerateProxy);
    }

    private static SpecialType ClassifySpecialType(ITypeSymbol type, KnownSymbols symbols)
    {
        return type as INamedTypeSymbol switch
        {
            { SpecialType: Microsoft.CodeAnalysis.SpecialType.System_Void } => SpecialType.Void,
            { IsGenericType: true } namedType when SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, symbols.TaskOfT) => SpecialType.Task,
            { IsGenericType: true } namedType when SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, symbols.ValueTaskOfT) => SpecialType.ValueTask,
            { IsGenericType: true } namedType when SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, symbols.IAsyncEnumerableOfT) => SpecialType.IAsyncEnumerable,
            { IsGenericType: false } namedType when SymbolEqualityComparer.Default.Equals(type, symbols.Task) => SpecialType.Task,
            { IsGenericType: false } namedType when SymbolEqualityComparer.Default.Equals(type, symbols.ValueTask) => SpecialType.ValueTask,
            { IsGenericType: false } namedType when SymbolEqualityComparer.Default.Equals(type, symbols.CancellationToken) => SpecialType.CancellationToken,
            _ => SpecialType.Other,
        };
    }

    private void GenerateProxy(SourceProductionContext context, DataModel? model)
    {
        if (model is null)
        {
            return;
        }

        string proxyClassName = $"{model.FileNamePrefix}_Proxy";

        SourceWriter writer = new();
        writer.WriteLine($$"""
            // <auto-generated/>

            #nullable enable

            namespace StreamJsonRpc.Proxies;

            internal class {{proxyClassName}}(
                global::StreamJsonRpc.JsonRpc client,
                global::StreamJsonRpc.JsonRpcProxyOptions options,
                long? marshaledObjectHandle,
                global::System.Action onDispose) : {{model.InterfaceName}}, global::StreamJsonRpc.IJsonRpcClientProxyInternal
            {
                private global::System.EventHandler<string>? callingMethod;
                private global::System.EventHandler<string>? calledMethod;
                private bool disposed;

                global::StreamJsonRpc.JsonRpc global::StreamJsonRpc.IJsonRpcClientProxy.JsonRpc => client;

                bool global::Microsoft.IDisposableObservable.IsDisposed => this.disposed;

                long? global::StreamJsonRpc.IJsonRpcClientProxyInternal.MarshaledObjectHandle => marshaledObjectHandle;

                event global::System.EventHandler<string> global::StreamJsonRpc.IJsonRpcClientProxyInternal.CallingMethod
                {
                    add => this.callingMethod += value;
                    remove => this.callingMethod -= value;
                }

                event global::System.EventHandler<string> global::StreamJsonRpc.IJsonRpcClientProxyInternal.CalledMethod
                {
                    add => this.calledMethod += value;
                    remove => this.calledMethod -= value;
                }

                public void Dispose()
                {
                    if (this.disposed)
                    {
                        return;
                    }
                    this.disposed = true;

                    if (onDispose is not null)
                    {
                        onDispose();
                    }
                    else
                    {
                        client.Dispose();
                    }
                }
            """);

        writer.Indentation++;
        foreach (MethodModel method in model.Methods)
        {
            string? cancellationTokenExpression = method.CancellationToken?.Name;
            string returnExpression = method.ReturnSpecialType switch
            {
                SpecialType.Void => string.Empty,
                SpecialType.Task => "result",
                SpecialType.ValueTask => $"new {method.ReturnType}(result)",
                SpecialType.IAsyncEnumerable => $"global::StreamJsonRpc.Reflection.CodeGenHelpers.CreateAsyncEnumerableProxy(result, {cancellationTokenExpression ?? "default"})",
                _ => throw new NotSupportedException($"Unsupported return type: {method.ReturnType}"),
            };

            // The possible methods we invoke are as follows:
            // | Return type | Named args | Signature
            // | Task        | Yes        | Task InvokeWithParameterObjectAsync(string targetName, object? argument, IReadOnlyDictionary<string, Type>? argumentDeclaredTypes, CancellationToken cancellationToken)
            // | Task<T>     | Yes        | Task<TResult> InvokeWithParameterObjectAsync<TResult>(string targetName, object? argument, IReadOnlyDictionary<string, Type>? argumentDeclaredTypes, CancellationToken cancellationToken)
            // | void        | Yes        | Task NotifyWithParameterObjectAsync(string targetName, object? argument, IReadOnlyDictionary<string, Type>? argumentDeclaredTypes)
            // | Task        | No         | Task InvokeWithCancellationAsync(string targetName, IReadOnlyList<object?>? arguments, IReadOnlyList<Type> argumentDeclaredTypes, CancellationToken cancellationToken)
            // | Task<T>     | No         | Task<TResult> InvokeWithCancellationAsync<TResult>(string targetName, IReadOnlyList<object?>? arguments, IReadOnlyList<Type>? argumentDeclaredTypes, CancellationToken cancellationToken)
            // | void        | No         | Task NotifyAsync(string targetName, object?[]? arguments, IReadOnlyList<Type>? argumentDeclaredTypes)
            string returnTypeArg = method.ReturnTypeArg is null ? string.Empty :
                method.ReturnSpecialType == SpecialType.IAsyncEnumerable ? $"<{method.ReturnType}>" :
                $"<{method.ReturnTypeArg}>";
            string namedArgsInvocationMethodName = method.ReturnSpecialType switch
            {
                SpecialType.Void => "NotifyWithParameterObjectAsync",
                SpecialType.Task or SpecialType.ValueTask or SpecialType.IAsyncEnumerable => $"InvokeWithParameterObjectAsync{returnTypeArg}",
                _ => throw new NotSupportedException($"Unsupported return type: {method.ReturnSpecialType}"),
            };
            string positionalArgsInvocationMethodName = method.ReturnSpecialType switch
            {
                SpecialType.Void => "NotifyAsync",
                SpecialType.Task or SpecialType.ValueTask or SpecialType.IAsyncEnumerable => $"InvokeWithCancellationAsync{returnTypeArg}",
                _ => throw new NotSupportedException($"Unsupported return type: {method.ReturnSpecialType}"),
            };

            string namedTypesFieldName = $"{method.Name}NamedArgumentDeclaredTypes";
            string positionalTypesFieldName = $"{method.Name}PositionalArgumentDeclaredTypes";
            writer.WriteLine($$"""
                private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> {{namedTypesFieldName}} = new global::System.Collections.Generic.Dictionary<string, global::System.Type>
                {
                """);
            writer.Indentation++;
            foreach (ParameterModel parameter in method.DataParameters.Span)
            {
                writer.WriteLine($"""["{parameter.Name}"] = typeof({parameter.Type}),""");
            }

            writer.Indentation--;
            writer.WriteLine("""
                };
                """);

            writer.WriteLine($$"""
                private static readonly global::System.Collections.Generic.IReadOnlyList<global::System.Type> {{positionalTypesFieldName}} = new global::System.Collections.Generic.List<global::System.Type>
                {
                """);
            writer.Indentation++;
            foreach (ParameterModel parameter in method.DataParameters.Span)
            {
                writer.WriteLine($"""typeof({parameter.Type}),""");
            }

            writer.Indentation--;
            writer.WriteLine("""
                };
                """);

            string namedArgsRecordName = $"{method.Name}NamedArgs";
            writer.WriteLine($"private record {namedArgsRecordName}({string.Join(", ", method.DataParameters.Select(p => $"{p.Type} {p.Name}"))});");

            string positionalArgs = "[" + string.Join(", ", method.DataParameters.Select(p => p.Name)) + "]";
            string namedArgs = $"new {namedArgsRecordName}({string.Join(", ", method.DataParameters.Select(p => p.Name))})";

            string cancellationArg = method.ReturnSpecialType == SpecialType.Void ? string.Empty : $", {method.CancellationToken?.Name ?? "default"}";

            writer.WriteLine($$"""

                public {{method.ReturnType}} {{method.Name}}({{string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"))}})
                {
                    if (this.disposed) throw new global::System.ObjectDisposedException(nameof({{proxyClassName}}));

                    this.callingMethod?.Invoke(this, "{{method.Name}}");
                    string rpcMethodName = options.MethodNameTransform("{{method.Name}}");
                    global::System.Threading.Tasks.Task{{returnTypeArg}} result = options.ServerRequiresNamedArguments ?
                        client.{{namedArgsInvocationMethodName}}(rpcMethodName, {{namedArgs}}, {{namedTypesFieldName}}{{cancellationArg}}) :
                        client.{{positionalArgsInvocationMethodName}}(rpcMethodName, {{positionalArgs}}, {{positionalTypesFieldName}}{{cancellationArg}});
                    this.calledMethod?.Invoke(this, "{{method.Name}}");

                    return {{returnExpression}};
                }
                """);
        }

        writer.Indentation--;
        writer.WriteLine("}");

        context.AddSource($"{model.FileNamePrefix}.g.cs", writer.ToSourceText());
    }

    private record DataModel(string FileNamePrefix, string InterfaceName, ImmutableEquatableArray<MethodModel> Methods);

    private record MethodModel(string Name, string ReturnType, SpecialType ReturnSpecialType, string? ReturnTypeArg, ImmutableEquatableArray<ParameterModel> Parameters)
    {
        internal bool TakesCancellationToken => this.Parameters.Length > 0 && this.Parameters[^1].SpecialType == SpecialType.CancellationToken;

        internal ParameterModel? CancellationToken => this.TakesCancellationToken ? this.Parameters[^1] : null;

        /// <summary>
        /// Gets a span over the parameters that exclude the <see cref="CancellationToken"/>.
        /// </summary>
        internal ReadOnlyMemory<ParameterModel> DataParameters => this.Parameters.AsMemory()[..(this.Parameters.Length - (this.TakesCancellationToken ? 1 : 0))];

        internal static MethodModel Create(IMethodSymbol method, KnownSymbols symbols)
        {
            return new MethodModel(
                method.Name,
                method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                ClassifySpecialType(method.ReturnType, symbols),
                method.ReturnType is INamedTypeSymbol { IsGenericType: true, TypeArguments: [ITypeSymbol typeArg] } ? typeArg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) : null,
                new([.. method.Parameters.Select(p => ParameterModel.Create(p, symbols))]));
        }
    }

    private record ParameterModel(string Name, string Type, SpecialType SpecialType)
    {
        internal static ParameterModel Create(IParameterSymbol parameter, KnownSymbols symbols)
            => new(parameter.Name, parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), ClassifySpecialType(parameter.Type, symbols));
    }
}
