// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using System.Reflection;
using Microsoft.CodeAnalysis;

namespace StreamJsonRpc.Analyzers;

/// <summary>
/// Source generator for StreamJsonRpc proxies.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class ProxyGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<DataModel?> proxyProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            Types.RpcProxyAttribute.FullName,
            (node, cancellationToken) => true,
            (context, cancellationToken) =>
            {
                if (context.TargetSymbol is not INamedTypeSymbol iface)
                {
                    return null;
                }

                ImmutableArray<MethodModel> methods = [..
                    iface.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Select(method => new MethodModel(
                        method.Name,
                        method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        [.. method.Parameters.Select(p => new ParameterModel(p.Name, p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))]))
                    ];

                string fileNamePrefix = context.TargetSymbol.ToDisplayString(GenerationHelpers.QualifiedNameOnlyFormat);
                return new DataModel(
                    fileNamePrefix,
                    context.TargetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    methods);
            });

        // TODO:
        // * Generate an interceptor for StreamJsonRpc methods that take RPC interfaces and generate proxies
        //   that redirects to methods that accept our source generated proxy types.

        context.RegisterSourceOutput(proxyProvider, this.GenerateProxy);
    }

    private void GenerateProxy(SourceProductionContext context, DataModel? model)
    {
        if (model is null)
        {
            return;
        }

        SourceWriter writer = new();
        writer.WriteLine($$"""
            // <auto-generated/>

            namespace StreamJsonRpc.Proxies;

            internal class RpcProxy(global::StreamJsonRpc.JsonRpc client) : {{model.InterfaceName}}
            {
            """);

        writer.Indentation++;
        bool first = true;
        foreach (MethodModel method in model.Methods)
        {
            if (!first)
            {
                writer.WriteLine();
            }

            first = false;
            writer.WriteLine($"public {method.ReturnType} {method.Name}({string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"))})");
            writer.WriteLine("{");
            writer.Indentation++;
            writer.WriteLine("throw new global::System.NotImplementedException();");
            writer.Indentation--;
            writer.WriteLine("}");
        }

        writer.Indentation--;
        writer.WriteLine("}");

        context.AddSource($"{model.FileNamePrefix}.g.cs", writer.ToSourceText());
    }

    private record DataModel(string FileNamePrefix, string InterfaceName, ImmutableArray<MethodModel> Methods);

    private record MethodModel(string Name, string ReturnType, ImmutableArray<ParameterModel> Parameters);

    private record ParameterModel(string Name, string Type);
}
