// <auto-generated/>

#nullable enable

namespace System.Runtime.CompilerServices
{
#pragma warning disable CS9113
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
    {
    }
#pragma warning restore CS9113
}

#pragma warning disable CS0436 // prefer local types to imported ones

namespace StreamJsonRpc.Generated
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	file static class StreamJsonRpcInterceptor
	{

		[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "bTx0/g/SpxgjV6JnJRbB220BAABUZXN0MC5jcw==")]
		internal static T AttachIMyService_Proxy<T>(global::System.IO.Stream stream)
		{
		    global::StreamJsonRpc.JsonRpc jsonRpc = new(stream);
		    IMyService_Proxy proxy = new(jsonRpc, null, null, null, null);
		    jsonRpc.StartListening();
		    return (T)(object)proxy;
		}
	}
}
