// <auto-generated/>

#nullable enable
#pragma warning disable CS0436 // prefer local types to imported ones

[global::StreamJsonRpc.Reflection.JsonRpcProxyMappingAttribute(typeof(StreamJsonRpc.Generated.IPublicService_Proxy))]
partial interface IPublicService
{
}

namespace StreamJsonRpc.Generated
{
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("StreamJsonRpc.Analyzers", "x.x.x.x")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public class IPublicService_Proxy : global::StreamJsonRpc.Reflection.ProxyBase
		, global::IPublicService
	{
		
		public IPublicService_Proxy(global::StreamJsonRpc.JsonRpc client, global::StreamJsonRpc.JsonRpcProxyOptions? options, long? marshaledObjectHandle, global::System.Action? onDispose, global::System.ReadOnlyMemory<global::System.Type>? requestedInterfaces)
		    : base(client, options, marshaledObjectHandle, onDispose, requestedInterfaces)
		{
		}
	}
}
