trigger:
  branches:
    include: ["master", "v1.4", "v1.5", "dev/andarno/hosted"]
  paths:
    exclude: ["doc", "*.md", ".appveyor.yml", ".travis.yml"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool: Hosted VS2017
  steps:
  - task: PowerShell@2
    displayName: Set VSTS variables
    inputs:
      targetType: inline
      script: |
        if ($env:SignType -eq 'Real') {
          $feedGuid = '09d8d03c-1ac8-456e-9274-4d2364527d99'
        } else {
          $feedGuid = 'da484c78-f942-44ef-b197-99e2a1bef53c'
        }

        Write-Host "##vso[task.setvariable variable=feedGuid]$feedGuid"

        if ($env:ComputerName.StartsWith('factoryvm', [StringComparison]::OrdinalIgnoreCase)) {
          Write-Host "Running on hosted queue"
          Write-Host "##vso[task.setvariable variable=Hosted]true"
        }

  - ${{ if eq('false', 'true') }}:
    - template: .azure-pipeline.microbuild.before.yml

  - template: build.yml
    parameters:
      build: all

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      projects: src/**/*.sln
      arguments: --no-build -c $(BuildConfiguration)

  - task: VSTest@2
    displayName: Run tests on .NET Framework (with code coverage)
    inputs:
      testFiltercriteria: TestCategory!=FailsInCloudTest
      searchFolder: $(System.DefaultWorkingDirectory)\bin
      testAssemblyVer2: |
        **\*tests*.dll
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      codeCoverageEnabled: true
    condition: and(succeeded(), ne(variables['SignType'], 'real'))

  - ${{ if eq('false', 'true') }}:
    - template: .azure-pipeline.microbuild.after.yml

  - task: CopyFiles@1
    inputs:
      Contents: |
        bin/**/$(BuildConfiguration)/**/StreamJsonRpc.*.nupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)/deployables
      flattenFolders: true
    displayName: Collecting deployables
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/deployables
      ArtifactName: deployables
      ArtifactType: Container
    displayName: Publish deployables artifacts
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- job: Linux
  pool:
    vmImage: Ubuntu 16.04
  variables:
    GitLinkEnabled: false
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core runtime 1.0.11
    inputs:
      packageType: runtime
      version: 1.0.11
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core runtime 1.1.8
    inputs:
      packageType: runtime
      version: 1.1.8
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core runtime 2.0.7
    inputs:
      packageType: runtime
      version: 2.0.7
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core SDK 2.1.300
    inputs:
      packageType: sdk
      version: 2.1.300
  - template: build.yml

- job: macOS
  pool:
    vmImage: macOS 10.13
  variables:
    GitLinkEnabled: false
  steps:
  - template: build.yml
