stages:
- stage: symbol_archive
  displayName: Symbol archival
  condition: and(succeeded(), eq(dependencies.Build.outputs['Windows.SetPipelineVariables.SignType'], 'Real'))
  jobs:
  - job: archive
    pool: VSEng-ReleasePool-1ES
    steps:
    - checkout: none
    - download: current
      artifact: Variables-Windows
      displayName: Download Variables-Windows artifact
    - task: PowerShell@2
      displayName: Set pipeline variables based on artifacts
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/Variables-Windows/_pipelines.ps1
    - download: current
      artifact: symbols-legacy
      displayName: Download symbols-legacy artifact
    - task: MicroBuildArchiveSymbols@1
      displayName: Archive symbols to Symweb
      inputs:
        SymbolsFeatureName: $(SymbolsFeatureName)
        SymbolsSymwebProject: VS
        SymbolsUncPath: \\cpvsbuild\drops\$(TeamName)\$(Build.DefinitionName)\$(Build.SourceBranchName)\$(Build.BuildId)\Symbols.Archival
        SymbolsEmailContacts: vsidemicrobuild
        SymbolsAgentPath: $(Pipeline.Workspace)/symbols-legacy
    - task: MicroBuildCleanup@1
      displayName: Send Telemetry

- stage: azure_public_vssdk_feed
  displayName: azure-public/vssdk feed
  condition: and(succeeded(), eq(dependencies.Build.outputs['Windows.SetPipelineVariables.SignType'], 'Real'))
  jobs:
  - job: push
    pool:
      name: AzurePipelines-EO
      vmImage: AzurePipelinesUbuntu20.04compliant
    steps:
    - checkout: none
    - download: current
      artifact: deployables-Windows
      displayName: Download deployables-Windows artifact
    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: sdk
        version: 6.x
    - task: NuGetAuthenticate@1
      displayName: Authenticate NuGet feeds
      inputs:
        nuGetServiceConnections: azure-public/vssdk
        forceReinstallCredentialProvider: true
    - script: dotnet nuget push $(Pipeline.Workspace)/deployables-Windows/NuGet/*.nupkg -s https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json --api-key azdo --skip-duplicate
      displayName: Push nuget packages
