trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
  pipelines:
  - pipeline: CI
    source: vs-StreamJsonRpc
    trigger:
      tags:
      - auto-release

variables:
- group: VS SDK feeds # Expected to provide NuGetOrgApiKey

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES

    stages:
    - stage: release
      jobs:
      - job: release
        pool:
          name: AzurePipelines-EO
          demands:
          - ImageOverride -equals AzurePipelinesUbuntu20.04compliantGPT
          os: Linux
        steps:
        - checkout: none
        - powershell: |
            Write-Host "##vso[build.updatebuildnumber]$(resources.pipeline.CI.runName)"
            if ('$(resources.pipeline.CI.runName)'.Contains('-')) {
              Write-Host "##vso[task.setvariable variable=IsPrerelease]true"
            } else {
              Write-Host "##vso[task.setvariable variable=IsPrerelease]false"
            }
          displayName: ⚙ Set up pipeline
        - task: UseDotNet@2
          displayName: ⚙ Install .NET SDK
          inputs:
            packageType: sdk
            version: 6.x
        - download: CI
          artifact: deployables-Windows
          displayName: 🔻 Download deployables-Windows artifact
          patterns: 'deployables-Windows/NuGet/*'
        - task: GitHubRelease@1
          displayName: 📢 GitHub release (create)
          inputs:
            gitHubConnection: AArnott
            repositoryName: $(Build.Repository.Name)
            target: $(resources.pipeline.CI.sourceCommit)
            tagSource: userSpecifiedTag
            tag: v$(resources.pipeline.CI.runName)
            title: v$(resources.pipeline.CI.runName)
            isDraft: true # After running this step, visit the new draft release, edit, and publish.
            isPreRelease: $(IsPrerelease)
            assets: $(Pipeline.Workspace)/CI/deployables-Windows/NuGet/*.nupkg
            changeLogCompareToRelease: lastNonDraftRelease
            changeLogType: issueBased
            changeLogLabels: |
              [
                { "label" : "breaking change", "displayName" : "Breaking changes", "state" : "closed" },
                { "label" : "bug", "displayName" : "Fixes", "state" : "closed" },
                { "label" : "enhancement", "displayName": "Enhancements", "state" : "closed" }
              ]
        - script: dotnet nuget push $(Pipeline.Workspace)/CI/deployables-Windows/NuGet/*.nupkg -s https://api.nuget.org/v3/index.json --api-key $(NuGetOrgApiKey) --skip-duplicate
          displayName: 📦 Push packages to nuget.org
          condition: and(succeeded(), ne(variables['NuGetOrgApiKey'], ''))
