jobs:
- job: RichCodeNavUpload
  displayName: Rich Code Navigation Upload to Staging
  pool: ${{ parameters.windowsPool }}
  condition: ne(variables['Build.Reason'], 'Schedule')
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK
    inputs:
      packageType: sdk
      version: 2.1.503
  - template: install-dependencies.yml
  - task: RichCodeNavIndexer@0
    displayName: RichCodeNav Upload
    inputs:
      languages: 'csharp'
      environment: staging
      isPrivateFeed: false
    continueOnError: true
