parameters:
  targetfx: ''
  runtime: ''

steps:
- script: env
  displayName: Confirm environment
  env:
    DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 0
    RuntimeFrameworkVersion: ${{ parameters.runtime }}
- script: format('dotnet build -v n -f {0} -c $(BuildConfiguration) --no-restore /bl:"$(Build.ArtifactStagingDirectory)/build_logs/{0}.binlog"', parameters.targetfx)
  displayName: format('Build test for {0}', parameters.targetfx)
  workingDirectory: src/StreamJsonRpc.Tests
- script: format('dotnet test -v n -f {0} -c $(BuildConfiguration) --no-build --filter "TestCategory!=FailsInCloudTest"', parameters.targetfx)
  displayName: format('Run tests for {0} on the .NET Core {1} runtime', parameters.targetfx, parameters.runtime)
  workingDirectory: src/StreamJsonRpc.Tests
  env:
    DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 0
    RuntimeFrameworkVersion: ${{ parameters.runtime }}
